name: 构建 PCL

on:
  push:
    paths:
      - 'Plain Craft Launcher 2.sln'
      - 'Plain Craft Launcher 2/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'Plain Craft Launcher 2.sln'
      - 'Plain Craft Launcher 2/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        include: 
        - name: 调试版
          configuration: Debug
        - name: 开发版
          configuration: Snapshot
        - name: 快照版
          configuration: Release
        - name: 更新快照版
          configuration: ReleaseUpdate
        - name: 正式版
          configuration: BETA
        
    runs-on: windows-latest

    env:
      Solution_Name: Plain Craft Launcher 2.sln
      Wap_Project_Directory: Plain Craft Launcher 2
      Wap_Project_Path: Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj
      Configuration: ${{ matrix.configuration }}
      Version_Friendly_Name: ${{ matrix.name }}

    steps:
    - name: 签出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # setup msbuild
    - name: 安装 MSBuild
      uses: microsoft/setup-msbuild@v2

    # # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: 编译源代码
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /t:Rebuild
    
    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.Version_Friendly_Name }}
        path: ${{ env.Wap_Project_Directory }}\obj\${{ env.Configuration }}\Plain Craft Launcher 2.exe
