name: Build

on:
  push:
    paths:
      - 'Plain Craft Launcher 2/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'Plain Craft Launcher 2/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:

  build:

    strategy: 
      matrix: 
        configuration: [Debug, Release, Snapshot, BETA, ReleaseUpdate]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Describe
      shell: bash
      run: |
          Describe=`git describe --tags --always`
          echo "Describe=$Describe" >> $GITHUB_ENV

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Replace
      shell: powershell
      env:
        client_id: ${{ secrets.client_id }}
        x-api-key: ${{ secrets.x_api_key }}
      run: |
        (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace '$client_id',   | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
        (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Client.Headers("x-api-key") = ""', '"Client.Headers("x-api-key") = "${{ secrets.x_api_key }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
        (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace '$client_id',  | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"

    - name: Build
      run: msbuild "Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj" -p:Configuration=${{ matrix.configuration }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }} ${{ env.Describe }}
        path: Plain Craft Launcher 2\obj\${{ matrix.configuration }}\Plain Craft Launcher 2.exe
