name: 构建 PCL

on:
  push:
    paths:
      - 'Plain Craft Launcher 2.sln'
      - 'Plain Craft Launcher 2/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release, Snapshot, BETA, ReleaseUpdate]

    runs-on: windows-latest

    env:
      Solution_Name: Plain Craft Launcher 2.sln
      Wap_Project_Directory: Plain Craft Launcher 2
      Wap_Project_Path: Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: 签出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # setup msbuild
    - name: 安装 MSBuild
      uses: microsoft/setup-msbuild@v2

    # # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration


    # Create the app package by building and packaging the Windows Application Packaging project
    - name: 编译 PCL
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /t:Rebuild
      # /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle
      # env:
      #   Appx_Bundle: Always
      #   Appx_Bundle_Platforms: x86|x64|ARM|ARM64
      #   Appx_Package_Build_Mode: StoreUpload

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.Configuration }}
        path: ${{ env.Wap_Project_Directory }}\obj\${{ env.Configuration }}\Plain Craft Launcher 2.exe
